import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { CalendarDays, Clock3, MapPin, Minus, Plus, ShieldCheck, TicketCheck } from "lucide-react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

declare global { interface Window { setAccount?: (key:string, software:string, version:string)=>void; getTokens?: (success:()=>void,failure:()=>void,timeout:number)=>void; setIfieldStyle?: (field:string,css:string)=>void; } }
type EventStatus = { remaining:number; capacity:number };

export default function EventsPage() {
  const [quantity,setQuantity]=useState(1), [status,setStatus]=useState<EventStatus|null>(null), [busy,setBusy]=useState(false), [error,setError]=useState("");
  const [confirmation,setConfirmation]=useState<{orderNumber:string;ticketCode:string}|null>(null);
  const formRef=useRef<HTMLFormElement>(null), total=useMemo(()=>quantity*20,[quantity]);
  useEffect(()=>{
    fetch("/api/events/live/status").then(r=>r.json()).then(setStatus).catch(()=>undefined);
    const script=document.createElement("script"); script.src="https://cdn.cardknox.com/ifields/3.5.2607.1401/ifields.min.js"; script.async=true;
    script.onload=()=>{ const key=import.meta.env.VITE_SOLA_IFIELDS_KEY; if(!key){setError("Ticket checkout is not configured yet.");return;} window.setAccount?.(key,"Latest Talks","1.0.0"); const css="font-family:Poppins,Arial,sans-serif;font-size:16px;color:#10213a;width:100%;height:46px;padding:0 12px;border:0;box-sizing:border-box;"; window.setIfieldStyle?.("card-number",css); window.setIfieldStyle?.("cvv",css); };
    document.body.appendChild(script); return()=>script.remove();
  },[]);
  function submitPurchase(event:FormEvent<HTMLFormElement>){ event.preventDefault();setError("");setBusy(true); if(!window.getTokens){setError("The secure payment fields are still loading. Please try again.");setBusy(false);return;} window.getTokens(async()=>{try{const form=new FormData(formRef.current!);const expiration=`${String(form.get("expMonth")||"").padStart(2,"0")}${form.get("expYear")}`;const response=await fetch("/api/events/live/purchase",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.get("name"),email:form.get("email"),phone:form.get("phone"),quantity,cardToken:form.get("xCardNum"),cvvToken:form.get("xCVV"),expiration,billingZip:form.get("billingZip")})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Payment could not be completed.");setConfirmation(data);window.scrollTo({top:0,behavior:"smooth"});}catch(err){setError(err instanceof Error?err.message:"Payment could not be completed.");}finally{setBusy(false);}},()=>{setError("Please check the card number and CVV, then try again.");setBusy(false);},30000); }
  if(confirmation)return <div className="min-h-screen bg-[#f0edeb] pt-16"><Header/><main className="mx-auto max-w-2xl px-4 py-20 text-center"><div className="rounded-2xl bg-white p-8 shadow-xl"><TicketCheck className="mx-auto h-16 w-16 text-green-600"/><h1 className="mt-5 text-3xl font-bold text-[#10213a]">You’re going!</h1><p className="mt-3 text-lg">Your ticket and barcode were emailed to you.</p><div className="mt-6 rounded-lg bg-slate-100 p-4 font-mono text-sm">{confirmation.orderNumber}<br/>{confirmation.ticketCode}</div><p className="mt-5 text-sm text-slate-600">Please bring the emailed ticket to the entrance.</p></div></main><Footer/></div>;
  return <div className="min-h-screen bg-[#f0edeb] pt-16"><Header/><main><section className="relative overflow-hidden bg-[#10213a] px-4 py-14 text-white md:py-20"><div className="absolute -right-24 -top-32 h-96 w-96 rounded-full bg-[#de2026]/25 blur-3xl"/><div className="relative mx-auto grid max-w-6xl gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><div className="mb-5 inline-flex rounded-full border border-red-400/40 bg-red-500/15 px-4 py-2 text-sm font-semibold text-red-200">Limited tickets available</div><h1 className="max-w-3xl text-4xl font-bold leading-tight md:text-6xl">Latest Talks<br/>Podcast Live</h1><div dir="rtl" className="mt-4 text-3xl font-bold text-red-400 md:text-5xl">התעורר־זיץ תשפ״ז</div><div className="mt-9 grid gap-4 text-base md:grid-cols-2"><p className="flex gap-3"><CalendarDays className="h-5 w-5 text-red-400"/>Thursday, September 17, 2026</p><p className="flex gap-3"><Clock3 className="h-5 w-5 text-red-400"/>7:45–11:00 PM</p><p className="flex gap-3 md:col-span-2"><MapPin className="h-5 w-5 shrink-0 text-red-400"/><span>Young Israel Beth El of Boro Park<br/>4802 15th Ave, Brooklyn, NY 11219</span></p></div></div><div className="rounded-2xl border border-white/15 bg-white/10 p-7 backdrop-blur"><div className="text-sm uppercase tracking-widest text-slate-300">Advance admission</div><div className="mt-2 text-6xl font-bold">$20</div><p className="mt-2 text-lg text-slate-200">$25 at the door. Save $5 when you buy online.</p><a href="#tickets"><Button className="mt-7 h-12 w-full bg-[#de2026] text-base hover:bg-red-700">Buy tickets</Button></a></div></div></section>
  <section id="tickets" className="mx-auto max-w-6xl px-4 py-14 md:py-20"><div className="grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><div><h2 className="text-3xl font-bold text-[#10213a]">Reserve your tickets</h2><p className="mt-3 text-slate-600">Your barcode ticket will arrive by email immediately after payment.</p><div className="mt-8 rounded-xl bg-[#10213a] p-6 text-white"><div className="flex items-center justify-between"><span>Tickets</span><div className="flex items-center gap-3"><Button type="button" size="icon" variant="outline" onClick={()=>setQuantity(q=>Math.max(1,q-1))} disabled={quantity===1}><Minus className="h-4 w-4"/></Button><strong className="w-6 text-center text-xl">{quantity}</strong><Button type="button" size="icon" variant="outline" onClick={()=>setQuantity(q=>Math.min(10,q+1))} disabled={quantity===10}><Plus className="h-4 w-4"/></Button></div></div><div className="mt-5 flex items-center justify-between border-t border-white/20 pt-5 text-xl"><span>Total</span><strong>${total}.00</strong></div></div></div>
  <form ref={formRef} onSubmit={submitPurchase} className="rounded-2xl bg-white p-6 shadow-xl md:p-8"><h3 className="text-2xl font-bold text-[#10213a]">Buyer and payment information</h3><div className="mt-6 grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><Label htmlFor="name">Full name</Label><Input id="name" name="name" required className="mt-2 h-12"/></div><div><Label htmlFor="email">Email</Label><Input id="email" name="email" type="email" required className="mt-2 h-12"/></div><div><Label htmlFor="phone">Phone</Label><Input id="phone" name="phone" type="tel" className="mt-2 h-12"/></div><div className="sm:col-span-2"><Label>Card number</Label><iframe title="Secure card number" data-ifields-id="card-number" data-ifields-placeholder="Card number" src="https://cdn.cardknox.com/ifields/3.5.2607.1401/ifield.htm" className="mt-2 h-12 w-full rounded-md border bg-white"/><input data-ifields-id="card-number-token" name="xCardNum" type="hidden"/></div><div><Label>Expiration</Label><div className="mt-2 grid grid-cols-2 gap-2"><Input name="expMonth" inputMode="numeric" placeholder="MM" maxLength={2} required/><Input name="expYear" inputMode="numeric" placeholder="YY" maxLength={2} required/></div></div><div><Label>CVV</Label><iframe title="Secure CVV" data-ifields-id="cvv" data-ifields-placeholder="CVV" src="https://cdn.cardknox.com/ifields/3.5.2607.1401/ifield.htm" className="mt-2 h-12 w-full rounded-md border bg-white"/><input data-ifields-id="cvv-token" name="xCVV" type="hidden"/></div><div className="sm:col-span-2"><Label htmlFor="billingZip">Billing ZIP</Label><Input id="billingZip" name="billingZip" inputMode="numeric" required className="mt-2 h-12"/></div></div><div data-ifields-id="card-data-error" className="mt-3 text-sm text-red-600"/>{error&&<div role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}<Button disabled={busy||status?.remaining===0} className="mt-6 w-full bg-[#de2026] py-6 text-base hover:bg-red-700">{busy?"Processing securely…":status?.remaining===0?"Sold out":`Purchase ${quantity} ticket${quantity>1?"s":""} — $${total}.00`}</Button><p className="mt-4 flex items-center justify-center gap-2 text-xs text-slate-500"><ShieldCheck className="h-4 w-4"/>Secure payment powered by Sola</p></form></div></section></main><Footer/></div>;
}
